sgt_activity:
    resource: "@SGTActivityBundle/Resources/config/routing.yml"
    prefix:   /activity

sgt_media:
    resource: "@SGTMediaBundle/Resources/config/routing.yml"
    prefix:   /

sgt_admin:
    resource: "@SGTAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

sgt_news:
    resource: "@SGTNewsBundle/Resources/config/routing.yml"
    prefix:   /news

sgt_content:
    resource: "@SGTContentBundle/Resources/config/routing.yml"
    prefix:   /

sgt_newsletter:
    resource: "@SGTNewsletterBundle/Resources/config/routing.yml"
    prefix:   /

sgt_core:
    resource: "@SGTCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile