sgt_activity:
    resource: "@SGTActivityBundle/Resources/config/routing.yml"
    prefix:   /activity

sgt_media:
    resource: "@SGTMediaBundle/Resources/config/routing.yml"
    prefix:   /

sgt_admin:
    resource: "@SGTAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

sgt_news:
    resource: "@SGTNewsBundle/Resources/config/routing.yml"
    prefix:   /news

sgt_content:
    resource: "@SGTContentBundle/Resources/config/routing.yml"
    prefix:   /

sgt_newsletter:
    resource: "@SGTNewsletterBundle/Resources/config/routing.yml"
    prefix:   /

sgt_core:
    resource: "@SGTCoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /login
    defaults:  { _controller: SGTUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

register:
    path:   /register
    defaults:  { _controller: SGTUserBundle:Security:register }

modify:
    path:   /modify/{id}
    defaults:  { _controller: SGTUserBundle:Security:modify, id: 0 }
