<?php

namespace SGT\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function getNews($page, $nbPerPage)
  	{
	    $queryBuilder = $this->createQueryBuilder('a');
	    $query = $queryBuilder->getQuery();

	    $query
	      ->setFirstResult(($page-1) * $nbPerPage)
	      ->setMaxResults($nbPerPage)
	    ;

	    return new Paginator($query, true);
  	}
}
