<?php

namespace SGT\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * mediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
	public function getMedias($page, $nbPerPage)
  	{
	    $queryBuilder = $this->createQueryBuilder('a');
	    $query = $queryBuilder->getQuery();

	    $query
	      // On définit l'annonce à partir de laquelle commencer la liste
	      ->setFirstResult(($page-1) * $nbPerPage)
	      // Ainsi que le nombre d'annonce à afficher sur une page
	      ->setMaxResults($nbPerPage)
	    ;

	    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
	    // (n'oubliez pas le use correspondant en début de fichier)
	    return new Paginator($query, true);
  	}
}
