sgt_admin_home:
    path:     /
    defaults: { _controller: SGTAdminBundle:Admin:index }


sgt_admin_content:
    path:     /content
    defaults: { _controller: SGTContentBundle:Content:index }

sgt_admin_add_role:
    path:     /content/role
    defaults: { _controller: SGTContentBundle:Content:role }
