sgt_admin_home:
    path:     /
    defaults: { _controller: SGTAdminBundle:Admin:index }

sgt_admin_content:
    path:     /content
    defaults: { _controller: SGTContentBundle:Content:index }

sgt_admin_add_role:
    path:     /content/role
    defaults: { _controller: SGTContentBundle:Content:role }

sgt_admin_add_user:
    path:     /user/add
    defaults: { _controller: SGTUserBundle:User:role }

sgt_admin_media:
    path:      /media/{page}
    defaults:  { _controller: SGTMediaBundle:Media:index, page: 1 }
    requirements:
        page: \d*
