<?php

namespace SGT\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRoleRepository extends EntityRepository
{
}
